rm -rf anat
rm -rf anat_mask
rm -rf bold_img
rm -rf bold_mask
rm -f fmap.json
rm -f fmri.json
rm -rf fmripinput
rm -rf out
rm -rf workdir
rm -f license.txt
rm -f multi_proc.yml
rm -f nohup.out
rm -rf output_report
rm -f product.json
rm -rf regress
rm -rf aroma  
rm -f t1w.json
rm -f t2w.json
rm -rf templateflow
rm -rf bids
