#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=9:00:00,vmem=14gb
#PBS -N fmriprep

set -x
set -e

bl2bids

#####################################################################################
#####################################################################################
#write out *plugin* configuration for fmriprep to limit mem/cpus
#this can't prevent the fmriprep/nipype bootup vmem spiking (could kill the job)
#but it seems to help...
cat <<EOF > multi_proc.yml
plugin: LegacyMultiProc
plugin_args: {maxtasksperchild: 1, memory_gb: 14, n_procs: 8, raise_insufficient: false}
EOF

#source bids_funcs.sh

WORKDIRNAME=work
outdir=out
#INDIRNAME=fmripinput

inT1w=`jq -r '.t1' config.json`
inT2w=`jq -r '.t2' config.json`
inFMRI=`jq -r '.fmri' config.json`
inFSDIR=`jq -r '.fsin' config.json`

space=$(jq -r .space config.json)

output_space=$space
cifti_output_resolution="91k" #could be 170k-higher resolution CIFTI output (170494 grayordinates @ 1.6mm).

#for volume output
resolution=$(jq -r .resolution config.json)
if [ $resolution != "original" ] && [ $resolution != "null" ] ;then
    output_space=$space:$resolution
fi

skipbidsvalidation=""
[ "$(jq -r .skipbidsvalidation config.json)" == "true" ] && skipbidsvalidation="--skip-bids-validation"

#####################################################################################
#####################################################################################
# some logical checks
if [[ $inT1w = "null" ]] || [[ $inFMRI = "null" ]] ; then
	echo "app needs minimally a T1w and fmri. exiting"
	exit 1
fi

# extract info from brainlife interface, base on T1w
# get the staging dir, this is where meta information is 
stagingDir=$(dirname $inT1w)
echo "ls dir where initial bl info read--> $stagingDir"
ls -dl $stagingDir

if [[ $stagingDir = "." ]]; then
   echo "error finding staging directory. exiting"
   exit 1
fi

#####################################################################################
#####################################################################################
# setup bids dir structure

# if freesurfer provided, copy it to the same level as output dir
# TODO why can't we just symlink this in?
if [[ $inFSDIR != "null" ]] ; then

    #clean up previous freesurfer dir if it exists
    rm -rf $outdir/freesurfer
    mkdir -p $outdir/freesurfer

    #TODO - strip alphanumeric chars?
    sub=$(jq -r '._inputs[] | select(.id == "t1w") | .meta.subject' config.json)
    cp -r $inFSDIR $outdir/freesurfer/sub-$sub
    chmod -R +rw $outdir/freesurfer
fi

# avoid templateflow problems on HPC's running singularity
mkdir -p templateflow
export SINGULARITYENV_TEMPLATEFLOW_HOME=$PWD/templateflow

# set FreeSurfer
[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

if [ ! -d $outdir/fmriprep ]; then

    #clean up previous workdir if it exist
    rm -rf $WORKDIRNAME && mkdir -p $WORKDIRNAME

    # TODO - I shouldn't set cifti-output if it's running in volume mode?
    time singularity exec -e \
        docker://nipreps/fmriprep:20.2.1 \
        /usr/local/miniconda/bin/fmriprep \
        --notrack \
        --resource-monitor \
        --md-only-boilerplate \
        --stop-on-first-crash \
        --use-plugin=multi_proc.yml \
        --output-spaces $output_space MNI152NLin2009cAsym \
        --cifti-output $cifti_output_resolution \
        --force-bbr \
        --use-syn-sdc \
        $skipbidsvalidation \
        --skull-strip-template=NKI \
        --work-dir=$WORKDIRNAME \
        --fs-license-file=license.txt \
        bids $outdir participant
fi

echo "done with fmriprep! - now organizing output"
./fmriprep2bl.sh

rm -r $WORKDIRNAME # save lots of space

echo "all done"

